"""
Mock data matching the real hackathon PostgreSQL schema.
Designed to be visually compelling for demo purposes.
On event day: set MOCK_MODE=false and connect to real DB.
"""

import json

# ── Dashboard Stats ──────────────────────────────────────────────────────────
MOCK_STATS = {
    "total_entities": 851300,
    "total_funding_loops": 5808,
    "total_fed_grants": 1275521,
    "total_ab_grants": 1986676,
    "total_sole_source": 15533,
    "total_charities": 85000,
    "zombie_count": 347,
    "multi_board_directors": 2841,
    "total_public_funding": 89_400_000_000,
    "at_risk_funding": 3_200_000_000,
}

# ── Zombie Recipients ────────────────────────────────────────────────────────
MOCK_ZOMBIES = [
    {
        "id": 1001,
        "canonical_name": "Northern Horizons Youth Foundation",
        "primary_bn": "812345678",
        "entity_type": "charity",
        "registration_status": "Revoked",
        "status_date": "2023-06-15",
        "designation": "B",
        "category": "welfare",
        "fed_funding": 4_250_000,
        "ab_funding": 1_800_000,
        "total_public_funding": 6_050_000,
        "last_filing_year": "2022",
        "dataset_sources": ["cra", "fed", "ab"],
        "addresses": [{"city": "Edmonton", "province": "AB"}],
        "risk_level": "critical",
        "govt_revenue_pct": 87,
    },
    {
        "id": 1002,
        "canonical_name": "Prairie Community Development Corp",
        "primary_bn": "823456789",
        "entity_type": "charity",
        "registration_status": "Annulled",
        "status_date": "2023-09-22",
        "designation": "A",
        "category": "community",
        "fed_funding": 3_120_000,
        "ab_funding": 890_000,
        "total_public_funding": 4_010_000,
        "last_filing_year": "2021",
        "dataset_sources": ["cra", "fed"],
        "addresses": [{"city": "Calgary", "province": "AB"}],
        "risk_level": "critical",
        "govt_revenue_pct": 92,
    },
    {
        "id": 1003,
        "canonical_name": "Maple Leaf Innovation Society",
        "primary_bn": "834567890",
        "entity_type": "charity",
        "registration_status": "Revoked",
        "status_date": "2024-01-10",
        "designation": "B",
        "category": "education",
        "fed_funding": 2_750_000,
        "ab_funding": 0,
        "total_public_funding": 2_750_000,
        "last_filing_year": "2023",
        "dataset_sources": ["cra", "fed"],
        "addresses": [{"city": "Ottawa", "province": "ON"}],
        "risk_level": "high",
        "govt_revenue_pct": 78,
    },
    {
        "id": 1004,
        "canonical_name": "Western Canada Skills Alliance",
        "primary_bn": "845678901",
        "entity_type": "charity",
        "registration_status": "Revoked",
        "status_date": "2023-03-28",
        "designation": "A",
        "category": "education",
        "fed_funding": 1_900_000,
        "ab_funding": 2_100_000,
        "total_public_funding": 4_000_000,
        "last_filing_year": "2022",
        "dataset_sources": ["cra", "fed", "ab"],
        "addresses": [{"city": "Red Deer", "province": "AB"}],
        "risk_level": "critical",
        "govt_revenue_pct": 95,
    },
    {
        "id": 1005,
        "canonical_name": "National Heritage Conservation Trust",
        "primary_bn": "856789012",
        "entity_type": "charity",
        "registration_status": "Voluntary Revocation",
        "status_date": "2022-12-05",
        "designation": "A",
        "category": "culture",
        "fed_funding": 1_650_000,
        "ab_funding": 450_000,
        "total_public_funding": 2_100_000,
        "last_filing_year": "2021",
        "dataset_sources": ["cra", "fed", "ab"],
        "addresses": [{"city": "Vancouver", "province": "BC"}],
        "risk_level": "high",
        "govt_revenue_pct": 71,
    },
    {
        "id": 1006,
        "canonical_name": "Great Lakes Environmental Research Inc",
        "primary_bn": "867890123",
        "entity_type": "charity",
        "registration_status": "Revoked",
        "status_date": "2024-02-14",
        "designation": "B",
        "category": "environment",
        "fed_funding": 980_000,
        "ab_funding": 0,
        "total_public_funding": 980_000,
        "last_filing_year": "2023",
        "dataset_sources": ["cra", "fed"],
        "addresses": [{"city": "Toronto", "province": "ON"}],
        "risk_level": "medium",
        "govt_revenue_pct": 65,
    },
    {
        "id": 1007,
        "canonical_name": "Arctic Outreach Ministries",
        "primary_bn": "878901234",
        "entity_type": "charity",
        "registration_status": "Annulled",
        "status_date": "2023-07-30",
        "designation": "A",
        "category": "religion",
        "fed_funding": 750_000,
        "ab_funding": 320_000,
        "total_public_funding": 1_070_000,
        "last_filing_year": "2022",
        "dataset_sources": ["cra", "fed", "ab"],
        "addresses": [{"city": "Yellowknife", "province": "NT"}],
        "risk_level": "high",
        "govt_revenue_pct": 83,
    },
    {
        "id": 1008,
        "canonical_name": "Boreal Health Initiative",
        "primary_bn": "889012345",
        "entity_type": "charity",
        "registration_status": "Revoked",
        "status_date": "2023-11-12",
        "designation": "B",
        "category": "health",
        "fed_funding": 2_400_000,
        "ab_funding": 600_000,
        "total_public_funding": 3_000_000,
        "last_filing_year": "2022",
        "dataset_sources": ["cra", "fed", "ab"],
        "addresses": [{"city": "Saskatoon", "province": "SK"}],
        "risk_level": "critical",
        "govt_revenue_pct": 91,
    },
]

# ── Funding Loops ────────────────────────────────────────────────────────────
MOCK_LOOPS = [
    {
        "id": 1,
        "hops": 3,
        "path_bns": ["119032856RR", "119212334RR", "118876432RR", "119032856RR"],
        "path_display": "Sunrise Foundation → Mountain Valley Charities → River Cities Trust → Sunrise Foundation",
        "bottleneck_amt": 2_340_000,
        "total_flow": 8_700_000,
        "min_year": 2021,
        "max_year": 2024,
        "same_year": True,
    },
    {
        "id": 2,
        "hops": 4,
        "path_bns": ["129876543RR", "138765432RR", "147654321RR", "156543210RR", "129876543RR"],
        "path_display": "National Housing Alliance → Urban Development Corp → Community Build Foundation → Social Infrastructure Inc → National Housing Alliance",
        "bottleneck_amt": 1_890_000,
        "total_flow": 12_400_000,
        "min_year": 2020,
        "max_year": 2024,
        "same_year": False,
    },
    {
        "id": 3,
        "hops": 2,
        "path_bns": ["167890123RR", "178901234RR", "167890123RR"],
        "path_display": "Heritage Arts Council → Creative Futures Society → Heritage Arts Council",
        "bottleneck_amt": 1_560_000,
        "total_flow": 3_200_000,
        "min_year": 2022,
        "max_year": 2024,
        "same_year": True,
    },
    {
        "id": 4,
        "hops": 5,
        "path_bns": ["189012345RR", "190123456RR", "201234567RR", "212345678RR", "223456789RR", "189012345RR"],
        "path_display": "Northern Wellness Fund → Indigenous Health Partners → Community Care Network → Families First Association → Children's Aid Foundation → Northern Wellness Fund",
        "bottleneck_amt": 1_200_000,
        "total_flow": 15_600_000,
        "min_year": 2020,
        "max_year": 2023,
        "same_year": False,
    },
    {
        "id": 5,
        "hops": 3,
        "path_bns": ["234567890RR", "245678901RR", "256789012RR", "234567890RR"],
        "path_display": "Education Forward Consortium → Literacy Now Canada → Skills Bridge Foundation → Education Forward Consortium",
        "bottleneck_amt": 980_000,
        "total_flow": 4_100_000,
        "min_year": 2021,
        "max_year": 2024,
        "same_year": True,
    },
    {
        "id": 6,
        "hops": 2,
        "path_bns": ["267890123RR", "278901234RR", "267890123RR"],
        "path_display": "Pacific Environmental Trust → Green Horizons Foundation → Pacific Environmental Trust",
        "bottleneck_amt": 870_000,
        "total_flow": 1_900_000,
        "min_year": 2022,
        "max_year": 2024,
        "same_year": True,
    },
]

# ── Loop Network Graph ───────────────────────────────────────────────────────
MOCK_LOOP_GRAPH = {
    "nodes": [
        {"id": "119032856", "name": "Sunrise Foundation", "revenue": 5_200_000, "circular_outflow": 2_340_000, "loops_count": 3, "risk": "high"},
        {"id": "119212334", "name": "Mountain Valley Charities", "revenue": 3_800_000, "circular_outflow": 1_900_000, "loops_count": 2, "risk": "high"},
        {"id": "118876432", "name": "River Cities Trust", "revenue": 4_100_000, "circular_outflow": 2_100_000, "loops_count": 2, "risk": "medium"},
        {"id": "129876543", "name": "National Housing Alliance", "revenue": 8_900_000, "circular_outflow": 1_890_000, "loops_count": 1, "risk": "medium"},
        {"id": "138765432", "name": "Urban Development Corp", "revenue": 6_200_000, "circular_outflow": 1_500_000, "loops_count": 1, "risk": "medium"},
        {"id": "147654321", "name": "Community Build Foundation", "revenue": 3_400_000, "circular_outflow": 1_200_000, "loops_count": 1, "risk": "low"},
        {"id": "156543210", "name": "Social Infrastructure Inc", "revenue": 2_900_000, "circular_outflow": 1_100_000, "loops_count": 1, "risk": "low"},
        {"id": "167890123", "name": "Heritage Arts Council", "revenue": 4_500_000, "circular_outflow": 1_560_000, "loops_count": 1, "risk": "high"},
        {"id": "178901234", "name": "Creative Futures Society", "revenue": 3_200_000, "circular_outflow": 1_560_000, "loops_count": 1, "risk": "high"},
        {"id": "189012345", "name": "Northern Wellness Fund", "revenue": 7_800_000, "circular_outflow": 1_200_000, "loops_count": 1, "risk": "medium"},
        {"id": "190123456", "name": "Indigenous Health Partners", "revenue": 5_600_000, "circular_outflow": 900_000, "loops_count": 1, "risk": "low"},
        {"id": "201234567", "name": "Community Care Network", "revenue": 4_300_000, "circular_outflow": 800_000, "loops_count": 1, "risk": "low"},
        {"id": "234567890", "name": "Education Forward Consortium", "revenue": 6_100_000, "circular_outflow": 980_000, "loops_count": 2, "risk": "medium"},
        {"id": "245678901", "name": "Literacy Now Canada", "revenue": 2_800_000, "circular_outflow": 750_000, "loops_count": 1, "risk": "low"},
        {"id": "256789012", "name": "Skills Bridge Foundation", "revenue": 3_600_000, "circular_outflow": 980_000, "loops_count": 1, "risk": "medium"},
    ],
    "links": [
        {"source": "119032856", "target": "119212334", "flow": 2_340_000, "loop_id": 1},
        {"source": "119212334", "target": "118876432", "flow": 2_900_000, "loop_id": 1},
        {"source": "118876432", "target": "119032856", "flow": 2_340_000, "loop_id": 1},
        {"source": "129876543", "target": "138765432", "flow": 1_890_000, "loop_id": 2},
        {"source": "138765432", "target": "147654321", "flow": 2_100_000, "loop_id": 2},
        {"source": "147654321", "target": "156543210", "flow": 1_890_000, "loop_id": 2},
        {"source": "156543210", "target": "129876543", "flow": 1_950_000, "loop_id": 2},
        {"source": "167890123", "target": "178901234", "flow": 1_560_000, "loop_id": 3},
        {"source": "178901234", "target": "167890123", "flow": 1_640_000, "loop_id": 3},
        {"source": "234567890", "target": "245678901", "flow": 980_000, "loop_id": 5},
        {"source": "245678901", "target": "256789012", "flow": 1_100_000, "loop_id": 5},
        {"source": "256789012", "target": "234567890", "flow": 980_000, "loop_id": 5},
    ],
}

# ── Governance Networks ──────────────────────────────────────────────────────
MOCK_GOVERNANCE = [
    {
        "last_name": "Richardson",
        "first_name": "James",
        "board_count": 7,
        "positions": ["Chair", "Director", "Treasurer"],
        "organizations": [
            {"bn_root": "812345678", "name": "Northern Horizons Youth Foundation", "entity_type": "charity", "fed_funding": "4250000", "cra_status": "Revoked"},
            {"bn_root": "119032856", "name": "Sunrise Foundation", "entity_type": "charity", "fed_funding": "2800000", "cra_status": "Registered"},
            {"bn_root": "129876543", "name": "National Housing Alliance", "entity_type": "charity", "fed_funding": "5100000", "cra_status": "Registered"},
            {"bn_root": "234567890", "name": "Education Forward Consortium", "entity_type": "charity", "fed_funding": "3200000", "cra_status": "Registered"},
            {"bn_root": "345678901", "name": "Community Health Network", "entity_type": "charity", "fed_funding": "1900000", "cra_status": "Registered"},
            {"bn_root": "456789012", "name": "Alberta Youth Services", "entity_type": "charity", "fed_funding": "2100000", "ab_funding": "1800000", "cra_status": "Registered"},
            {"bn_root": "567890123", "name": "Prairie Skills Development", "entity_type": "charity", "fed_funding": "1500000", "cra_status": "Registered"},
        ],
        "total_controlled_funding": 21_650_000,
        "risk_flags": ["Zombie entity in portfolio", "Cross-funding between entities", "7 boards exceeds governance norms"],
    },
    {
        "last_name": "Chen",
        "first_name": "Margaret",
        "board_count": 5,
        "positions": ["Director", "Secretary"],
        "organizations": [
            {"bn_root": "167890123", "name": "Heritage Arts Council", "entity_type": "charity", "fed_funding": "1800000", "cra_status": "Registered"},
            {"bn_root": "178901234", "name": "Creative Futures Society", "entity_type": "charity", "fed_funding": "1200000", "cra_status": "Registered"},
            {"bn_root": "678901234", "name": "Cultural Preservation Fund", "entity_type": "charity", "fed_funding": "2400000", "cra_status": "Registered"},
            {"bn_root": "789012345", "name": "Arts Outreach Canada", "entity_type": "charity", "fed_funding": "900000", "cra_status": "Registered"},
            {"bn_root": "890123456", "name": "National Museums Alliance", "entity_type": "charity", "fed_funding": "3100000", "cra_status": "Registered"},
        ],
        "total_controlled_funding": 9_400_000,
        "risk_flags": ["Two entities in funding loop (Heritage Arts ↔ Creative Futures)", "Concentrated in culture sector"],
    },
    {
        "last_name": "Williams",
        "first_name": "David",
        "board_count": 4,
        "positions": ["Chair", "Director"],
        "organizations": [
            {"bn_root": "823456789", "name": "Prairie Community Development Corp", "entity_type": "charity", "fed_funding": "3120000", "cra_status": "Annulled"},
            {"bn_root": "189012345", "name": "Northern Wellness Fund", "entity_type": "charity", "fed_funding": "4200000", "cra_status": "Registered"},
            {"bn_root": "901234567", "name": "Health Equity Foundation", "entity_type": "charity", "fed_funding": "2800000", "cra_status": "Registered"},
            {"bn_root": "112345678", "name": "Social Determinants Research Inc", "entity_type": "charity", "fed_funding": "1600000", "cra_status": "Registered"},
        ],
        "total_controlled_funding": 11_720_000,
        "risk_flags": ["Annulled entity in portfolio", "Director of entity in 5-hop funding loop"],
    },
    {
        "last_name": "Patel",
        "first_name": "Sunita",
        "board_count": 4,
        "positions": ["Director", "Vice-Chair"],
        "organizations": [
            {"bn_root": "845678901", "name": "Western Canada Skills Alliance", "entity_type": "charity", "fed_funding": "1900000", "ab_funding": "2100000", "cra_status": "Revoked"},
            {"bn_root": "245678901", "name": "Literacy Now Canada", "entity_type": "charity", "fed_funding": "1800000", "cra_status": "Registered"},
            {"bn_root": "256789012", "name": "Skills Bridge Foundation", "entity_type": "charity", "fed_funding": "2200000", "cra_status": "Registered"},
            {"bn_root": "367890123", "name": "Workforce Development Institute", "entity_type": "charity", "fed_funding": "1400000", "cra_status": "Registered"},
        ],
        "total_controlled_funding": 9_400_000,
        "risk_flags": ["Revoked entity in portfolio", "Two entities in funding loop (Literacy Now ↔ Skills Bridge)"],
    },
    {
        "last_name": "Thompson",
        "first_name": "Robert",
        "board_count": 3,
        "positions": ["Director"],
        "organizations": [
            {"bn_root": "138765432", "name": "Urban Development Corp", "entity_type": "charity", "fed_funding": "3800000", "cra_status": "Registered"},
            {"bn_root": "147654321", "name": "Community Build Foundation", "entity_type": "charity", "fed_funding": "2100000", "cra_status": "Registered"},
            {"bn_root": "478901234", "name": "Infrastructure Partnerships Canada", "entity_type": "charity", "fed_funding": "4500000", "cra_status": "Registered"},
        ],
        "total_controlled_funding": 10_400_000,
        "risk_flags": ["Two entities in same 4-hop funding loop"],
    },
]

# ── Entity Search Results ────────────────────────────────────────────────────
MOCK_ENTITIES = [
    {"id": 1001, "canonical_name": "Northern Horizons Youth Foundation", "entity_type": "charity", "bn_root": "812345678", "dataset_sources": ["cra", "fed", "ab"], "source_link_count": 47, "confidence": 0.95, "fed_total": 4250000, "ab_total": 1800000, "cra_status": "Revoked"},
    {"id": 1002, "canonical_name": "Prairie Community Development Corp", "entity_type": "charity", "bn_root": "823456789", "dataset_sources": ["cra", "fed"], "source_link_count": 31, "confidence": 0.92, "fed_total": 3120000, "ab_total": 890000, "cra_status": "Annulled"},
    {"id": 2001, "canonical_name": "Sunrise Foundation", "entity_type": "charity", "bn_root": "119032856", "dataset_sources": ["cra", "fed"], "source_link_count": 58, "confidence": 0.98, "fed_total": 2800000, "ab_total": 0, "cra_status": "Registered"},
    {"id": 2002, "canonical_name": "Mountain Valley Charities", "entity_type": "charity", "bn_root": "119212334", "dataset_sources": ["cra", "fed", "ab"], "source_link_count": 42, "confidence": 0.96, "fed_total": 1900000, "ab_total": 500000, "cra_status": "Registered"},
    {"id": 2003, "canonical_name": "National Housing Alliance", "entity_type": "charity", "bn_root": "129876543", "dataset_sources": ["cra", "fed", "ab"], "source_link_count": 89, "confidence": 0.99, "fed_total": 5100000, "ab_total": 3200000, "cra_status": "Registered"},
    {"id": 2004, "canonical_name": "Heritage Arts Council", "entity_type": "charity", "bn_root": "167890123", "dataset_sources": ["cra", "fed"], "source_link_count": 36, "confidence": 0.94, "fed_total": 1800000, "ab_total": 0, "cra_status": "Registered"},
    {"id": 2005, "canonical_name": "Education Forward Consortium", "entity_type": "charity", "bn_root": "234567890", "dataset_sources": ["cra", "fed", "ab"], "source_link_count": 64, "confidence": 0.97, "fed_total": 3200000, "ab_total": 1100000, "cra_status": "Registered"},
    {"id": 2006, "canonical_name": "Urban Development Corp", "entity_type": "charity", "bn_root": "138765432", "dataset_sources": ["cra", "fed"], "source_link_count": 51, "confidence": 0.93, "fed_total": 3800000, "ab_total": 0, "cra_status": "Registered"},
]

# ── Entity Dossiers ──────────────────────────────────────────────────────────
MOCK_ENTITY_DOSSIERS = {
    1001: {
        "id": 1001,
        "canonical_name": "Northern Horizons Youth Foundation",
        "entity_type": "charity",
        "bn_root": "812345678",
        "bn_variants": ["812345678RR0001"],
        "aliases": ["NORTHERN HORIZONS YOUTH FNDN", "N.H.Y.F.", "NHYF"],
        "dataset_sources": ["cra", "fed", "ab"],
        "source_link_count": 47,
        "confidence": 0.95,
        "addresses": [{"line1": "123 Northern Ave", "city": "Edmonton", "province": "AB", "postal": "T5J 1S9"}],
        "cra_profile": {
            "registration_status": "Revoked",
            "designation": "B",
            "category": "welfare",
            "registration_date": "2008-03-15",
            "effective_date": "2023-06-15",
            "latest_filing_year": 2022,
            "total_revenue_5yr": 12_800_000,
            "total_expenditure_5yr": 13_200_000,
            "govt_funding_pct": 87,
            "directors_count": 5,
            "filing_history": [
                {"year": 2022, "revenue": 2_100_000, "expenditures": 2_400_000, "govt_pct": 89},
                {"year": 2021, "revenue": 2_800_000, "expenditures": 2_900_000, "govt_pct": 85},
                {"year": 2020, "revenue": 3_100_000, "expenditures": 3_000_000, "govt_pct": 88},
            ],
        },
        "fed_profile": {
            "total_funding": 4_250_000,
            "grant_count": 12,
            "departments": ["Employment and Social Development Canada", "Canadian Heritage"],
            "earliest_grant": "2015-04-01",
            "latest_grant": "2022-09-15",
            "top_programs": ["Youth Employment Strategy", "Community Development Fund"],
        },
        "ab_profile": {
            "total_funding": 1_800_000,
            "grant_count": 8,
            "contract_count": 2,
            "ministries": ["Children's Services", "Community and Social Services"],
        },
        "related_entities": [
            {"id": 1002, "name": "Prairie Community Development Corp", "relationship": "RELATED", "shared_directors": 2},
        ],
        "risk_flags": [
            "Status revoked while receiving $6M+ in public funding",
            "87% government-dependent revenue",
            "Expenditures exceeded revenue in final years",
            "Shares 2 directors with another funded entity",
        ],
        "source_links": [
            {"source_schema": "cra", "source_table": "cra_identification", "source_name": "NORTHERN HORIZONS YOUTH FOUNDATION", "match_method": "bn_exact", "match_confidence": 1.0},
            {"source_schema": "fed", "source_table": "grants_contributions", "source_name": "Northern Horizons Youth Fndn", "match_method": "splink", "match_confidence": 0.94},
            {"source_schema": "ab", "source_table": "ab_grants", "source_name": "NORTHERN HORIZONS YOUTH FOUNDATION", "match_method": "deterministic", "match_confidence": 0.98},
        ],
    },
}


# ── Multi-Flag Alerts (Cross-Challenge Intersections) ────────────────────────
MOCK_ALERTS = [
    {
        "id": "alert-001",
        "entity_id": 1001,
        "canonical_name": "Northern Horizons Youth Foundation",
        "bn_root": "812345678",
        "alarm_count": 3,
        "total_public_funding": 6_050_000,
        "flags": [
            {
                "type": "zombie",
                "severity": "critical",
                "label": "Zombie Recipient",
                "detail": "Charity status Revoked Jun 2023. Received $6.05M in public funding across CRA, Federal, and Alberta streams.",
            },
            {
                "type": "governance",
                "severity": "high",
                "label": "Governance Concentration",
                "detail": "Director James Richardson sits on 7 funded charity boards simultaneously, controlling $21.6M total.",
            },
            {
                "type": "dependency",
                "severity": "critical",
                "label": "Government Dependency",
                "detail": "87% of revenue from government sources. Entity could not survive without public funding.",
            },
        ],
        "addresses": [{"city": "Edmonton", "province": "AB"}],
    },
    {
        "id": "alert-002",
        "entity_id": 2004,
        "canonical_name": "Heritage Arts Council",
        "bn_root": "167890123",
        "alarm_count": 3,
        "total_public_funding": 4_500_000,
        "flags": [
            {
                "type": "loop",
                "severity": "critical",
                "label": "Funding Loop",
                "detail": "Participates in 2-hop circular loop with Creative Futures Society. $1.56M bottleneck, same-year transactions suggest potential receipt inflation.",
            },
            {
                "type": "governance",
                "severity": "high",
                "label": "Director Cross-Membership",
                "detail": "Director Margaret Chen sits on both loop participants (Heritage Arts + Creative Futures), a direct conflict of interest.",
            },
            {
                "type": "concentration",
                "severity": "medium",
                "label": "Sector Concentration",
                "detail": "5 of Chen's 5 board seats are in the culture/arts sector — same grant programs, same department funders.",
            },
        ],
        "addresses": [{"city": "Ottawa", "province": "ON"}],
    },
    {
        "id": "alert-003",
        "entity_id": 1002,
        "canonical_name": "Prairie Community Development Corp",
        "bn_root": "823456789",
        "alarm_count": 3,
        "total_public_funding": 4_010_000,
        "flags": [
            {
                "type": "zombie",
                "severity": "critical",
                "label": "Zombie Recipient",
                "detail": "Charity status Annulled Sep 2023. $4.01M in public funding received — last filing year 2021.",
            },
            {
                "type": "governance",
                "severity": "high",
                "label": "Governance Overlap",
                "detail": "Director David Williams chairs this annulled entity AND the Northern Wellness Fund (active, $4.2M fed funding). Same director, different risk profiles.",
            },
            {
                "type": "loop",
                "severity": "medium",
                "label": "Network Proximity",
                "detail": "Williams is also a director in Northern Wellness Fund, which is a node in a 5-hop, $15.6M circular funding loop.",
            },
        ],
        "addresses": [{"city": "Calgary", "province": "AB"}],
    },
    {
        "id": "alert-004",
        "entity_id": 2005,
        "canonical_name": "Education Forward Consortium",
        "bn_root": "234567890",
        "alarm_count": 2,
        "total_public_funding": 4_300_000,
        "flags": [
            {
                "type": "loop",
                "severity": "high",
                "label": "Multiple Funding Loops",
                "detail": "Appears in 2 separate circular funding loops. Part of 3-hop loop with Literacy Now and Skills Bridge ($980K bottleneck).",
            },
            {
                "type": "governance",
                "severity": "high",
                "label": "Director on Revoked Entity",
                "detail": "Director Sunita Patel also chairs Western Canada Skills Alliance — revoked charity that received $4M in public funding.",
            },
        ],
        "addresses": [{"city": "Ottawa", "province": "ON"}],
    },
]


# ── Sole Source / Amendment Creep (Challenge #4) ─────────────────────────────
MOCK_SOLE_SOURCE = [
    {
        "id": 1,
        "vendor": "Acme Strategic Advisors Inc",
        "department": "Children's Services",
        "province": "AB",
        "original_amount": 48_500,
        "amended_amount": 893_000,
        "amendment_ratio": 18.4,
        "amendment_count": 7,
        "contract_date": "2021-03-15",
        "latest_amendment_date": "2023-11-28",
        "duration_months": 32,
        "justification": "Sole source — specialized expertise",
        "risk_flags": [
            "Original award just below $50K competitive threshold",
            "18.4x amendment growth over 32 months",
            "7 separate amendments — pattern of scope creep",
        ],
        "risk_level": "critical",
        "related_contracts": 4,
    },
    {
        "id": 2,
        "vendor": "NorthStar Consulting Group Ltd",
        "department": "Community and Social Services",
        "province": "AB",
        "original_amount": 74_900,
        "amended_amount": 1_240_000,
        "amendment_ratio": 16.6,
        "amendment_count": 5,
        "contract_date": "2020-09-01",
        "latest_amendment_date": "2023-07-14",
        "duration_months": 34,
        "justification": "Sole source — urgency / proprietary system",
        "risk_flags": [
            "16.6x amendment growth",
            "Vendor received 4 additional sole-source contracts from same department",
            "Urgency justification used for 34-month engagement",
        ],
        "risk_level": "critical",
        "related_contracts": 4,
    },
    {
        "id": 3,
        "vendor": "Pinnacle IT Solutions Corp",
        "department": "Alberta Health Services",
        "province": "AB",
        "original_amount": 49_800,
        "amended_amount": 682_500,
        "amendment_ratio": 13.7,
        "amendment_count": 6,
        "contract_date": "2022-01-10",
        "latest_amendment_date": "2024-06-30",
        "duration_months": 29,
        "justification": "Sole source — proprietary software maintenance",
        "risk_flags": [
            "Original award $200 below $50K threshold",
            "13.7x amendment growth",
            "Contract splitting suspected — 3 sibling contracts at $49,500 each with same vendor",
        ],
        "risk_level": "critical",
        "related_contracts": 3,
    },
    {
        "id": 4,
        "vendor": "Meridian Policy Group",
        "department": "Treasury Board and Finance",
        "province": "AB",
        "original_amount": 95_000,
        "amended_amount": 710_000,
        "amendment_ratio": 7.5,
        "amendment_count": 4,
        "contract_date": "2021-07-22",
        "latest_amendment_date": "2024-01-15",
        "duration_months": 30,
        "justification": "Sole source — incumbent vendor, continuity",
        "risk_flags": [
            "7.5x amendment growth",
            "'Continuity' justification used 4 times — suggests locked-in vendor relationship",
            "Vendor is registered lobbyist with Alberta government",
        ],
        "risk_level": "high",
        "related_contracts": 2,
    },
    {
        "id": 5,
        "vendor": "CloudBridge Technologies Inc",
        "department": "Service Alberta",
        "province": "AB",
        "original_amount": 125_000,
        "amended_amount": 580_000,
        "amendment_ratio": 4.6,
        "amendment_count": 3,
        "contract_date": "2022-11-01",
        "latest_amendment_date": "2024-08-31",
        "duration_months": 22,
        "justification": "Sole source — emergency procurement",
        "risk_flags": [
            "Emergency procurement extended 22 months",
            "4.6x amendment growth on 'emergency' contract",
            "Same vendor won competitive bid in 2019 for similar scope",
        ],
        "risk_level": "high",
        "related_contracts": 1,
    },
    {
        "id": 6,
        "vendor": "Prairie HR Consulting Ltd",
        "department": "Advanced Education",
        "province": "AB",
        "original_amount": 48_000,
        "amended_amount": 196_000,
        "amendment_ratio": 4.1,
        "amendment_count": 2,
        "contract_date": "2023-04-01",
        "latest_amendment_date": "2024-03-31",
        "duration_months": 12,
        "justification": "Sole source — specialized HR expertise",
        "risk_flags": [
            "Original award $2K below $50K threshold",
            "4.1x growth within 12 months",
        ],
        "risk_level": "medium",
        "related_contracts": 0,
    },
]

MOCK_SOLE_SOURCE_STATS = {
    "total_sole_source_contracts": 15_533,
    "total_original_value": 312_000_000,
    "total_amended_value": 891_000_000,
    "avg_amendment_ratio": 2.86,
    "contracts_over_5x": 847,
    "contracts_over_10x": 203,
    "top_department": "Children's Services",
    "total_at_risk": 579_000_000,
}
